[workspace]
members = ["cargo:jmap_dumper", "cargo:jmap", "cargo:usmap", "cargo:ue_binja"]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.2"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-pc-windows-msvc"]
# Enable distribution
dist = true
# Allow manual edits to CI files
allow-dirty = ["ci"]
